name: Go

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Run tests
        run: go test -v ./...
